import Head from 'next/head'
import styles from '../styles/style.module.scss'
import Currencies from "../components/Currencies.jsx";
import {Provider} from "react-redux";
import {store} from '../redux/store'

const Home = () => {

  return (
    <Provider store={store} >
        <div>
            <Head>
                <title>Currencies</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main className={styles.main}>
                <Currencies />
            </main>
        </div>
    </Provider>
  )
}
export default Home
